### ISSUE TITLE
Auto-fill password not detected

### ISSUE THREAD

**Issue by okwme** [portis-project/portis-sdk#19]
I'm on an iphone and trying to use a password keychain (1password in my case). It fills in both email and password but when I click submit it thinks there is no password entered.

**Comment by radotzki** [comment]
@okwme that a known issue (https://bugzilla.mozilla.org/show_bug.cgi?id=950510), happens on most of the browsers and also in react (https://github.com/facebook/react/issues/1159).
We will fix it in the next version of Portis (in a couple of days) 👍

**Comment by radotzki** [comment]
Fixed in our new SDK:
https://github.com/portis-project/web-sdk
