### ISSUE TITLE
Cannot access accounts

### ISSUE THREAD

**Issue by sonicsmith** [portis-project/portis-sdk#4]
Normally when I make a transaction in web3, I get the address of the user with: `web3.eth.accounts[0]`.

At the moment when Portis is being used as the provider, `web3.eth.accounts` is an empty array.

Accessing the contract seems to work fine in other respects though, just can't make transaction calls.

**Comment by tom-portis** [comment]
Hey @sonicsmith , in MetaMask, when the account is locked the behaviour will be the same. Soon, it will be the same until the user explicitly signs in with MetaMask (https://github.com/MetaMask/metamask-extension/issues/714#issuecomment-298368978). 
With Portis, the behaviour is already like that, as we are not an installed plugin, so until the user enters their credentials, they will not be signed in, hence there will be no accounts.

Therefore, the proper way of fetching the available user accounts is with the async method of `getAccounts`, which will prompt the user for his Portis credentials and subsequently populate the accounts array. This will allow you to get the account value from the array in a synchronous manner from the point onwards.

Please let us know if that resolves your problem so we can close this issue.

**Comment by sonicsmith** [comment]
That's it! Thanks so much, working great now :)

**Comment by tom-portis** [comment]
Glad to hear! closing the issue
