### ISSUE TITLE
Hardware wallet support: Ledger, TREZOR, ...

### ISSUE THREAD

**Issue by nakov** [portis-project/portis-sdk#6]
This client-side wallet would be more powerful if you add **hardware wallet support**, e.g. Ledger Nano, TREZOR, others. Crypto people trust more to their hardware wallets than to some SDK.

Currently, Portis does not give much benefits to using a client-side wallet or library like Ethers.js. I use such client-side wallets for my dApps for years: https://github.com/nakov/client-side-ethereum-wallet

**Comment by tom-portis** [comment]
Hi @nakov , thank you for taking an interest in Portis! 

Hardware wallet support is definitely something we want to add down the line, but in our vision, you'll place large sums in a smart contract where your Trezor PK can withdraw everything at once, but your Portis PK can withdraw smaller amounts per day, letting you enjoy the best of both worlds. If you'll need to pull out your Trezor whenever you want to buy a cryptokitty I think the UX will be terrible - for tech-savvy people, it'll be a hassle, and for non-technical people, it's a nightmare.

To clarify, Portis also creates a standard BIP39 wallet for any new account, but as opposed to ethers.js, it employs E2E encryption, which allows you to securely and privately access the same account on all your devices. Also, in ethers.js the wallet is saved to the client itself, which is both insecure and means that if you lose your phone, your wallet is gone (with Portis, the unencrypted wallet never leaves the process memory). Ethers.js does let you back up your wallet manually, but for the average user, that's another point of friction which they probably will be too lazy to carry out. Finally, as far as I know, ethers.js is not a web3 provider, meaning you can't use it to interact with DApps. 

We invite you to try Portis out in one of your Dapps, and if you have any more questions, let's continue this discussion on our gitter channel 🙏🏻:

https://gitter.im/portis-project/Lobby
