### ISSUE TITLE
Provide an explicit “user successfully logged in with Portis” event

### ISSUE THREAD

**Issue by tomteman** [portis-project/portis-sdk#9]
Currently, when a dapp calls any web3 method which requires the user to login (for instance getAccounts), there is no way of knowing if the callback was successful since the user just logged in to Portis successfully, or if they were already logged in, so the callback was invoked successfully without having to show the login window to the user.

To allow dapps to detect when the user logged in successfully to their Portis account, the Portis web3 provider will begin emitting events using the `.on('eventName', callback)` scheme, starting with `.on('login', callback)`.

e.g.

    web3.currentProvider.on('login', callback);

The `'login'` callback data object will contain the following fields:

    provider: the value will be 'portis'
    address: the wallet address the user sign in with

**Comment by radotzki** [comment]
Resolved by 0acba3c598177d814e460ae7fa2a06649132bd10
